### ISSUE TITLE
when one paragraph answer 'yes' or 'no',are all the doc_spans from that paragraph keeps as train features?

### ISSUE THREAD

**Issue by helloword12345678** [shmsw25/single-hop-rc#1]
thanks for sharing:
  i want to ask features in train process,in the file prepro.py, function convert_examples_to_features()。 
one article has multi paragraphs(which called doc_tokens), and one paragraph generate multi doc_spans.
 if one paragraph's answer is 'yes' or 'no',then all the doc_spans generate by  that paragraph  will keep as  train features of 'yes' or 'no'?--for example,one paragraph answer is 'yes' or 'no',and the paragraph formed 10 doc_spans,then all the 10 doc_spans are keep as train features of 'yes' or 'no'?????
is my understanding  right?

**Comment by shmsw25** [comment]
Hi @helloword12345678, thanks for asking. You are right, if the answer is 'yes' or 'no', then each of 10 paragraphs is always considered to have 'yes' or 'no' answer during training. However, at inference time only one of 10 paragraphs with the lowerest y_empty is considered. You can think it as the most naive way to deal with Yes/No question.
