### ISSUE TITLE
Torch: not enough memory

### ISSUE THREAD

**Issue by Simons2017** [shmsw25/single-hop-rc#2]
Hello! My graphics card is NVIDIA GeForce GTX 1080Ti, I have set train_batch_size=1,but still meet this problem.
Traceback (most recent call last):
  File "main.py", line 350, in <module>
    main()
  File "main.py", line 194, in main
    tokenizer=tokenizer)
  File "/home/cai/yym/ddl/single-hop-rc-master/prepro.py", line 43, in get_dataloader
    all_segment_ids = torch.tensor([f.segment_ids for f in train_features], dtype=torch.long)
RuntimeError: $ Torch: not enough memory: you tried to allocate 2GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:201

Do you have some good ideas？

**Comment by shmsw25** [comment]
Hi @Simons2017, it looks like your RAM is out of memory. This part is not related to `train_batch_size`, so I guess decreasing `train_batch_size` will not be helpful. Some suggestions I have are
- Decreasing `max_seq_length` (Not sure if it would guarantee the performance reported in the paper)
- Split train data to multiple files, and iterate loading one file, training the model on it, loading another file, and so on.
